name: Publish Docker images

on:
  pull_request:
    branches:
      - master
    types:
      - closed

jobs:
  tags:
    runs-on: ubuntu-latest
    if: github.event.pull_request.user.login == 'github-actions' && github.event.pull_request.merged == true

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Get package
        id: get_package
        run: echo ::set-output name=result::$(echo ${{ github.event.pull_request.head.ref }} | sed -E 's/^(.+)\/.+$/\1/')

      - name: Get version
        id: get_version
        run: echo ::set-output name=result::$(echo ${{ github.event.pull_request.head.ref }} | sed -E 's/^.+\/(.+)$/\1/')

      - name: Print
        run: |
          echo package ${{ steps.get_package.outputs.result }}
          echo version ${{ steps.get_version.outputs.result }}

      - name: Login
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login -u ${{ github.actor }} --password-stdin docker.pkg.github.com

      - name: Publish
        run: make --file ${{ steps.get_package.outputs.result }}/Makefile publish version=${{ steps.get_version.outputs.result }}
