name: Check for updates and open a PR

on:
  schedule:
    # every 8 hours
    - cron:  '0 */8 * * *'

jobs:
  check:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        package:
          - chromium
          # - firefox

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Get version
        id: get_version
        run: echo ::set-output name=result::$(make --file ${{ matrix.package }}/Makefile get-version)

      - name: Check status
        id: check_status
        run: echo ::set-output name=result::$(git tag | grep -q ${{ matrix.package }}@${{ steps.get_version.outputs.result }} && echo 'up-to-date' || echo 'outdated')

      - name: Make changes
        if: steps.check_status.outputs.result == 'outdated'
        run: sed -Ei 's/version-.+-blue/version-'${{ steps.get_version.outputs.result }}'-blue/' ${{ matrix.package }}/readme.md

      - name: Open a PR
        if: steps.check_status.outputs.result == 'outdated'
        uses: peter-evans/create-pull-request@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: ♻️ ${{ matrix.package }} ${{ steps.get_version.outputs.result }}
          body: https://www.chromestatus.com/features/schedule
          commit-message: ♻️ ${{ matrix.package }} ${{ steps.get_version.outputs.result }}
          branch: ${{ matrix.package }}/${{ steps.get_version.outputs.result }}
