name: Check for updates

on:
  repository_dispatch:
    types: check
  schedule:
    # every 12 hours
    - cron:  '0 */12 * * *'

jobs:
  check:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        package:
          - chromium
          # - firefox

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # https://github.com/actions/checkout#Fetch-all-tags
      - name: Fetch tags
        run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*

      - name: Get version
        id: get_version
        run: echo ::set-output name=result::$(make --file ${{ matrix.package }}/Makefile get-version)

      - name: Check status
        id: check_status
        run: echo ::set-output name=result::$(git tag | grep --quiet ${{ matrix.package }}@${{ steps.get_version.outputs.result }} && echo 'up-to-date' || echo 'outdated')

      - name: Print results
        run: |
          echo version: ${{ steps.get_version.outputs.result }}
          echo status: ${{ steps.check_status.outputs.result }}

      - name: Publish
        if: steps.check_status.outputs.result == 'outdated'
        run: |
          curl --header 'Accept: application/vnd.github.everest-preview+json' --header 'Authorization: token ${{ secrets.GITHUB_TOKEN }}' --request POST --data '{"event_type": "publish", "client_payload": { "package": "${{ matrix.package }}", "version": "${{ steps.get_version.outputs.result }}" }}' https://api.github.com/repos/${GITHUB_REPOSITORY}/dispatches
