name: Check for updates

on:
  repository_dispatch:
    types: check
  schedule:
    # every 12 hours
    - cron:  '0 */12 * * *'

jobs:
  check:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        package:
          - chromium
          - firefox

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # https://github.com/actions/checkout#Fetch-all-tags
      - name: Fetch tags
        run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*

      - name: Get version
        id: get_version
        run: echo ::set-output name=result::$(make --file ${{ matrix.package }}/Makefile get-version)

      - name: Check status
        id: check_status
        run: echo ::set-output name=result::$(git tag | grep --quiet ${{ matrix.package }}@${{ steps.get_version.outputs.result }} && echo 'up-to-date' || echo 'outdated')

      - name: Print results
        run: |
          echo package: ${{ matrix.package }}
          echo version: ${{ steps.get_version.outputs.result }}
          echo status: ${{ steps.check_status.outputs.result }}

    outputs:
      package: ${{ matrix.package }}
      version: ${{ steps.get_version.outputs.result }}
      status: ${{ steps.check_status.outputs.result }}

  update:
    runs-on: ubuntu-latest
    needs: check
    if: needs.check.outputs.status == 'outdated'

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build image
        run: make --file ${{ needs.check.outputs.package }}/Makefile build version=${{ needs.check.outputs.version }}

      - name: Test
        run: make --file ${{ needs.check.outputs.package }}/Makefile test

      - name: Get image size
        id: get_size
        run: |
          docker save ${{ needs.check.outputs.package }} | gzip > ${{ needs.check.outputs.package }}.tar.gz
          echo ::set-output name=result::$(du --human-readable --apparent-size ${{ needs.check.outputs.package }}.tar.gz | cut --fields=1)
          rm ${{ needs.check.outputs.package }}.tar.gz

      - name: Git setup
        run: |
          git config --global user.name 'GitHub'
          git config --global user.email 'noreply@github.com'
          git remote set-url origin https://${GITHUB_ACTOR}:${{ secrets.GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git

      - name: Git pull
        run: git pull origin master

      - name: Update readme
        run: |
          sed --regexp-extended --in-place 's/version\/[[:alnum:].]+\/blue/version\/'${{ needs.check.outputs.version }}'\/blue/' ${{ needs.check.outputs.package }}/readme.md
          sed --regexp-extended --in-place 's/size\/[[:alnum:].]+\/blue/size\/'${{ steps.get_size.outputs.result }}'\/blue/' ${{ needs.check.outputs.package }}/readme.md

      - name: Git commit
        run: git commit --message '♻️ ${{ needs.check.outputs.package }}@${{ needs.check.outputs.version }}' ${{ needs.check.outputs.package }}/readme.md

      - name: Make Docker and Git tags
        run: make --file ${{ needs.check.outputs.package }}/Makefile tags version=${{ needs.check.outputs.version }}

      - name: Git push
        run: git push --force --tags origin master

      - name: Docker GitHub Packages login
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login --username ${{ github.actor }} --password-stdin docker.pkg.github.com

      - name: Docker GitHub Packages push
        run: docker push docker.pkg.github.com/nextools/images/${{ needs.check.outputs.package }}

      - name: Docker Hub login
        run: echo ${{ secrets.DOCKER_HUB_TOKEN }} | docker login --username nextoolsbot --password-stdin

      - name: Docker Hub push
        run: docker push nextools/${{ needs.check.outputs.package }}
